-- automatically generated by BNF Converter
{-# LANGUAGE FlexibleContexts #-}

module Main where


import System.IO ( stdin, hGetContents )
import System.Environment ( getArgs, getProgName )

import Lexgram
import Pargram
import Skelgram
import Printgram
import Absgram
import Evalgram
import Preprocess



import ErrM

type ParseFun a = [Token] -> Err a

myLLexer = myLexer

type Verbosity = Int

putStrV :: Verbosity -> String -> IO ()
putStrV v s = if v > 1 then putStrLn s else return ()

runFile :: (Print Program, Show Program) => Verbosity -> ParseFun Program -> FilePath -> IO ()
runFile v p f = putStrLn f >> readFile f >>= run v p

run :: (Print Program, Show Program) => Verbosity -> ParseFun Program -> String -> IO ()
run v p s = let ts = myLLexer (preprocessInput s) in case p ts of
           Bad z    -> do putStrLn "\nParse              Failed...\n"
                          putStrV v "Tokens:"
                          putStrV v $ show ts
                          putStrLn $ show (preprocessInput s)
                          putStrLn z
           Ok  tree -> do (ans, tstore) <- checkProgram tree
                          if ans then do
                            putStrLn $ "Eval\n"
                            i <- evalProgram tree
                            putStrLn $ "\n[End State]\n\n" ++ (show i)
                          else
                            putStrLn $ "\n Type check failed\n" ++ (show tstore)
                          showTree v tree



showTree :: (Show Program, Print Program) => Int -> Program -> IO ()
showTree v tree
 = do
      putStrV v $ "\n[Abstract Syntax]\n\n" ++ show tree
      putStrV v $ "\n[Linearized tree]\n\n" ++ printTree tree

main :: IO ()
main = do args <- getArgs
          case args of
            [] -> hGetContents stdin >>= run 2 pProgram
            "-s":fs -> mapM_ (runFile 0 pProgram) fs
            fs -> mapM_ (runFile 2 pProgram) fs





